[2025-06-20T08:23:36.560+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-20T08:23:36.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-19T00:00:00+00:00 [queued]>
[2025-06-20T08:23:36.579+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-19T00:00:00+00:00 [queued]>
[2025-06-20T08:23:36.579+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 9
[2025-06-20T08:23:36.584+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_tweets> on 2025-06-19 00:00:00+00:00
[2025-06-20T08:23:36.588+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl_dag', 'extract_tweets', 'scheduled__2025-06-19T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/twitter_etl_dag.py', '--cfg-path', '/tmp/tmp74ltzi0b']
[2025-06-20T08:23:36.591+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask extract_tweets
[2025-06-20T08:23:36.590+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=288) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-20T08:23:36.592+0000] {standard_task_runner.py:63} INFO - Started process 289 to run task
[2025-06-20T08:23:36.615+0000] {task_command.py:426} INFO - Running <TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-19T00:00:00+00:00 [running]> on host 931f0b327f52
[2025-06-20T08:23:36.654+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='twitter_etl_dag' AIRFLOW_CTX_TASK_ID='extract_tweets' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T00:00:00+00:00'
[2025-06-20T08:23:36.654+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-20T08:23:36.940+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-20T08:23:36.942+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/twitter_etl_dag.py", line 36, in extract_tweets
    user = client.get_user(username='elonmusk')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 2359, in get_user
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 115, in request
    raise TooManyRequests(response)
tweepy.errors.TooManyRequests: 429 Too Many Requests
Too Many Requests
[2025-06-20T08:23:36.955+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_etl_dag, task_id=extract_tweets, run_id=scheduled__2025-06-19T00:00:00+00:00, execution_date=20250619T000000, start_date=20250620T082336, end_date=20250620T082336
[2025-06-20T08:23:36.968+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task extract_tweets (429 Too Many Requests
Too Many Requests; 289)
[2025-06-20T08:23:36.988+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-20T08:23:37.004+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-20T08:23:37.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
