[2025-06-20T10:16:38.467+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-20T10:16:38.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: twitter_etl_dag.extract_tweets manual__2025-06-20T10:16:37.934276+00:00 [queued]>
[2025-06-20T10:16:38.486+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: twitter_etl_dag.extract_tweets manual__2025-06-20T10:16:37.934276+00:00 [queued]>
[2025-06-20T10:16:38.487+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2025-06-20T10:16:38.494+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_tweets> on 2025-06-20 10:16:37.934276+00:00
[2025-06-20T10:16:38.499+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=181) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-20T10:16:38.500+0000] {standard_task_runner.py:63} INFO - Started process 184 to run task
[2025-06-20T10:16:38.499+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl_dag', 'extract_tweets', 'manual__2025-06-20T10:16:37.934276+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/twitter_etl_dag.py', '--cfg-path', '/tmp/tmp169ircxg']
[2025-06-20T10:16:38.501+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask extract_tweets
[2025-06-20T10:16:38.522+0000] {task_command.py:426} INFO - Running <TaskInstance: twitter_etl_dag.extract_tweets manual__2025-06-20T10:16:37.934276+00:00 [running]> on host 931f0b327f52
[2025-06-20T10:16:38.563+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='twitter_etl_dag' AIRFLOW_CTX_TASK_ID='extract_tweets' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T10:16:37.934276+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-20T10:16:37.934276+00:00'
[2025-06-20T10:16:38.564+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-20T10:16:39.186+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-20T10:16:39.188+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/twitter_etl_dag.py", line 38, in extract_tweets
    response = client.get_users_tweets(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 1587, in get_users_tweets
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 115, in request
    raise TooManyRequests(response)
tweepy.errors.TooManyRequests: 429 Too Many Requests
Usage cap exceeded: Monthly product cap
[2025-06-20T10:16:39.204+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_etl_dag, task_id=extract_tweets, run_id=manual__2025-06-20T10:16:37.934276+00:00, execution_date=20250620T101637, start_date=20250620T101638, end_date=20250620T101639
[2025-06-20T10:16:39.215+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task extract_tweets (429 Too Many Requests
Usage cap exceeded: Monthly product cap; 184)
[2025-06-20T10:16:39.233+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-20T10:16:39.249+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-20T10:16:39.250+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
