[2025-06-21T08:28:33.239+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-21T08:28:33.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-20T00:00:00+00:00 [queued]>
[2025-06-21T08:28:33.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-20T00:00:00+00:00 [queued]>
[2025-06-21T08:28:33.260+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2025-06-21T08:28:33.265+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_tweets> on 2025-06-20 00:00:00+00:00
[2025-06-21T08:28:33.269+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl_dag', 'extract_tweets', 'scheduled__2025-06-20T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/twitter_etl_dag.py', '--cfg-path', '/tmp/tmpq1da116i']
[2025-06-21T08:28:33.274+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask extract_tweets
[2025-06-21T08:28:33.274+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=186) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-21T08:28:33.276+0000] {standard_task_runner.py:63} INFO - Started process 187 to run task
[2025-06-21T08:28:33.304+0000] {task_command.py:426} INFO - Running <TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-20T00:00:00+00:00 [running]> on host 217110b24371
[2025-06-21T08:28:33.349+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='twitter_etl_dag' AIRFLOW_CTX_TASK_ID='extract_tweets' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-20T00:00:00+00:00'
[2025-06-21T08:28:33.350+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-21T08:28:33.953+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-21T08:28:33.954+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/twitter_etl_dag.py", line 38, in extract_tweets
    response = client.get_users_tweets(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 1587, in get_users_tweets
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/client.py", line 115, in request
    raise TooManyRequests(response)
tweepy.errors.TooManyRequests: 429 Too Many Requests
Usage cap exceeded: Monthly product cap
[2025-06-21T08:28:33.966+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_etl_dag, task_id=extract_tweets, run_id=scheduled__2025-06-20T00:00:00+00:00, execution_date=20250620T000000, start_date=20250621T082833, end_date=20250621T082833
[2025-06-21T08:28:34.022+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task extract_tweets (429 Too Many Requests
Usage cap exceeded: Monthly product cap; 187)
[2025-06-21T08:28:34.055+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-21T08:28:34.070+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-21T08:28:34.071+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
